[workspace]
resolver = "2"
members = [
    "crates/noise-types",
    "crates/noise-core",
    "crates/noise-io",
    "crates/noise-cli",
    "desktop/src-tauri",
]

[workspace.package]
version = "0.1.0"
authors = ["Zenfish"]
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
